### ISSUE TITLE
Xiaomi Redmi 2 / Prime

### ISSUE THREAD

**Issue by rem3rem3** [xiaomi-firmware-updater/mi-firmware-updater#1]
Will you add support for a Redmi 2?

**Comment by yshalsager** [comment]
I think there's no weekly developer rom for redmi 2, so I can't add it to weekly devices.
But if it's updated to miui 9 stable I can add it.

**Comment by yshalsager** [comment]
@rem3rem3 device added!
firmware files will be uploaded soon
https://github.com/xiaomi-firmware-updater/mi-firmware-updater/blob/stable/devices#L1
https://github.com/xiaomi-firmware-updater/mi-firmware-updater/blob/stable/devices#L1
